version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: downtown_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      NODE_ENV: production
